In [19]:
import warnings
warnings.filterwarnings("ignore")

### Importing the libraries

In [3]:
import sys
print(sys.executable)

/Users/macbook/Documents/Code/Machine-Learning-Projects/tf-env/bin/python

In [4]:
# basic + dates 
import numpy as np
import pandas as pd
from datetime import datetime

# data visualization
import matplotlib.pyplot as plt
import seaborn as sns # advanced vizs
%matplotlib inline

# statistics
from statsmodels.distributions.empirical_distribution import ECDF

# time series analysis
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# # prophet by Facebook
# from fbprophet import Prophet

### Geting the Data

In [5]:
rossmann_df  = pd.read_csv("./dataset/train.csv")
store_df     = pd.read_csv("./dataset/store.csv")
test_df      = pd.read_csv("./dataset/test.csv")


rossmann_df.head()

/var/folders/gk/q9d5jbtj33j94vb3kz2vgk4h0000gn/T/ipykernel_6030/887812119.py:1: DtypeWarning: Columns (0: StateHoliday) have mixed types. Specify dtype option on import or set low_memory=False.
  rossmann_df  = pd.read_csv("./dataset/train.csv")

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1

In [6]:
print(rossmann_df.shape)

(1017209, 9)

In [7]:
store_df.head()

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [8]:
corr = rossmann_df.corr(numeric_only=True)['Sales'].sort_values(ascending=False)
print(corr)

Sales            1.000000
Customers        0.894711
Open             0.678472
Promo            0.452345
SchoolHoliday    0.085124
Store            0.005126
DayOfWeek       -0.462125
Name: Sales, dtype: float64